name = "DoubleFloats"
uuid = "497a8b3b-efae-58df-a0af-a86822472b78"
keywords = ["math", "floating-point", "doubledouble", "extended-precision", "accuracy", "precision"]
license = "MIT"
desc = "extended precision floating point types using value pairs"
repo = "https://github.com/JuliaMath/DoubleFloats.jl.git"
version = "1.2.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Polynomials = "1, 2, 3"
Quadmath = "0.4, 0.5, 0.6"
Requires = "1"
SpecialFunctions = "0.7, 0.8, 0.9, 0.10, 1.0, 1.1, 2"
GenericLinearAlgebra = "0.2.5, 0.3, 0.4, 0.5, 0.6"
Combinatorics = "1"
julia = "1"

[extras]
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
GenericSchur = "c145ed77-6b09-5dd9-b285-bf645a82121e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SpecialFunctions", "GenericLinearAlgebra", "GenericSchur", "Combinatorics"]
